[package]
name = "wombatclient"
version = "0.1.0"
authors = ["Andy Dunstall <andydunstall@hotmail.com>"]
edition = "2018"

[dependencies]
crc = "1.8.1"
tokio = { version = "0.2", features = ["full"] }
wombatcore = { path = "../core" }
