[package]
name = "wombat"
version = "0.0.1"
authors = ["Andy Dunstall <andydunstall@hotmail.com>"]
edition = "2018"

[lib]
name = "wombat"
path = "src/lib.rs"

[[bin]]
name = "broker"
path = "src/main.rs"

[dependencies]
