cc_library(
    name = "log",
    srcs = glob(["src/*.cpp"]),
    hdrs = glob(["include/log/*.h"]),
    strip_include_prefix = "include/",
    linkopts = ["-lstdc++fs"],
    visibility = ["//visibility:public"],
)
