version: 2.1

jobs:
  commit-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Commit stage
          command: |
            sudo apt install curl gnupg
            curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
            echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
            sudo apt update && sudo apt install bazel -y

            bazel build ...
            bazel test ...

            sudo apt-get install -y python3-pip
            pip3 install cpplint
            ./bin/analize.sh

workflows:
  broker:
    jobs:
      - commit-stage
