version: 2.1

jobs:
  commit-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Commit stage
          command: |
            sudo apt-get install -y cmake
            cd log
            make install
            make -j 4
            make -j 4 unittest

  integration-test-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Integration Test stage
          command: |
            sudo apt-get install -y cmake
            cd log
            make install
            make -j 4 integrationtest


workflows:
  log:
    jobs:
      - commit-stage
      - integration-test-stage:
          requires:
            - commit-stage
