version: 2.1

jobs:
  broker-build:
    docker:
      - image: circleci/rust:1.41

    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd broker
            cargo build

  broker-unit-test:
    docker:
      - image: circleci/rust:1.41

    steps:
      - checkout
      - run:
          name: Unit test
          command: |
            cd broker
            cargo test

  client-build:
    docker:
      - image: circleci/golang:1.14.2

    steps:
      - checkout
      - run:
          name: Unit test
          command: |
            cd client
            go test ./...

  client-unit-test:
    docker:
      - image: circleci/golang:1.14.2

    steps:
      - checkout
      - run:
          name: Unit test
          command: |
            cd client
            go test ./...


workflows:
  broker:
    jobs:
      - broker-build
      - broker-unit-test
      - hold:
          type: approval
          requires:
            - broker-build
            - broker-unit-test


  client:
    jobs:
      - client-build
      - client-unit-test
      - hold:
          type: approval
          requires:
            - client-build
            - client-unit-test
