version: 2.1

jobs:
  commit-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - restore_cache:
          keys:
            - ~/.cache
      - run:
          name: Commit stage
          command: |
            ./bin/bazelisk build ...
            ./bin/bazelisk test ...
      - save_cache:
          key: bazel
          paths:
            - ~/.cache

workflows:
  broker:
    jobs:
      - commit-stage
