version: 2.1

jobs:
  commit-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Commit stage
          command: |
            sudo apt-get install -y cmake
            sudo ./bin/install.sh
            sudo ./bin/installtest.sh

            ./bin/exec.py build
            ./bin/exec.py unittest


  integration-test-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Integration Test stage
          command: |
            sudo apt-get install -y cmake
            sudo ./bin/install.sh
            sudo ./bin/installtest.sh

            ./bin/exec.py build
            ./bin/exec.py integrationtest


workflows:
  broker:
    jobs:
      - commit-stage
      - integration-test-stage:
          requires:
            - commit-stage
