version: 2.1

jobs:
  log-commit-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Commit stage
          command: |
            sudo apt-get install -y cmake
            cd log
            sudo make install
            sudo make installtest
            make -j 4
            make -j 4 unittest

  log-integration-test-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Integration Test stage
          command: |
            sudo apt-get install -y cmake
            cd log
            sudo make install
            sudo make installtest
            make -j 4 integrationtest

  partition-commit-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Commit stage
          command: |
            sudo apt-get install -y cmake
            # TODO(AD) Use output of log commit stage
            cd log
            sudo make install
            sudo make installtest
            make -j 4
            cd ..
            cd partition
            sudo make install
            sudo make installtest
            make -j 4
            # TODO(AD) Unit tests

  partition-integration-test-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Integration Test stage
          command: |
            sudo apt-get install -y cmake
            # TODO(AD) Use output of log commit stage
            cd log
            sudo make install
            sudo make installtest
            make -j 4
            cd ..
            cd partition
            sudo make install
            sudo make installtest
            make integrationtest

  server-commit-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Commit stage
          command: |
            sudo apt-get install -y cmake
            cd server
            sudo make install
            sudo make installtest
            make -j 4
            # TODO(AD) Unit tests

  server-integration-test-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Integration Test stage
          command: |
            sudo apt-get install -y cmake
            # TODO(AD) Use output of log commit stage
            cd server
            sudo make install
            sudo make installtest
            make integrationtest

  record-commit-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Commit stage
          command: |
            sudo apt-get install -y cmake
            cd record
            sudo make install
            sudo make installtest
            make -j 4
            make -j 4 unittest


workflows:
  log:
    jobs:
      - log-commit-stage
      - log-integration-test-stage:
          requires:
            - log-commit-stage

  partition:
    jobs:
      - partition-commit-stage
      - partition-integration-test-stage:
          requires:
            - partition-commit-stage

  server:
    jobs:
      - server-commit-stage
      - server-integration-test-stage:
          requires:
            - server-commit-stage

  record:
    jobs:
      - record-commit-stage
