version: 2.1

jobs:
  commit-stage:
    docker:
      - image: circleci/buildpack-deps:latest

    steps:
      - checkout
      - run:
          name: Commit stage
          command: |
            sudo apt-get install -y cmake
            cd partition
            make install
            make
            make unittest

workflows:
  broker:
    jobs:
      - commit-stage
