version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@0.0.10

jobs:
  commit-stage:
    docker:
      - image: circleci/rust:1.41

    steps:
      - checkout
      - run:
          name: Commit Stage
          command: |
            cargo build
            cargo test

workflows:
  broker:
    jobs:
      - commit-stage
      # TODO(AD) Add acc tests - for this have a API to call directly to put
      # and get - then a thin network layer tested independentry (makes tests easier)
