[package]
name = "broker"
version = "0.1.0"
authors = ["Andy Dunstall <andydunstall@hotmail.com>"]
edition = "2018"
description = "Distributed message system server"
readme = "README.md"
license = "MIT"

[dependencies]
