[package]
name = "broker"
version = "0.1.0"
authors = ["Andy Dunstall <andydunstall@hotmail.com>"]
edition = "2018"

[dependencies]
wombatlog = { path = "../log" }
wombatpartition = { path = "../partition" }

[dev-dependencies]
rand = "0.7.3"
tokio = { version = "0.2", features = ["full"] }
