[package]
name = "broker"
version = "0.1.0"
authors = ["Andy Dunstall <andydunstall@hotmail.com>"]
edition = "2018"

[dependencies]
wombatlog = { path = "../log" }
wombatpartition = { path = "../partition" }

[dev-dependencies]
tempdir = "0.3"
