[package]
name = "wombatpartition"
version = "0.1.0"
authors = ["Andy Dunstall <andydunstall@hotmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
wombatlog = { path = "../log" }

[dev-dependencies]
rand = "0.7.3"
tokio = { version = "0.2", features = ["full"] }
